import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import SuperAdminDashboard from './view/dashboard/SuperAdminDashboard'
import ViewClient from './view/clients/ViewClient'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const title= 'Dashboard'
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com crossorigin" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet"></link>
        {/* <script type="module" src="module.tsx"></script> */}
      </Head>
      <main className='bg-gray-50 min-h-screen'>
         <Header title={title} />
         <div className='p-4 px-9'>
          <SuperAdminDashboard />
         </div>
      </main>
    </>
  )
}
